version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: student_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - app-network

  spring-rest-api:
    image: spring-rest-api:v1
    container_name: spring-rest-api-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/student_db
      SPRING_DATASOURCE_USERNAME: user1
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
