apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-ebs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: "vol-0964e95dba54615ac"
    fsType: ext4
